changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 'New Features'
      labels:
        - 'feature'
        - 'enhancement'
    - title: 'Bug Fixes'
      labels:
        - 'fix'
        - 'bug'
    - title: 'Infrastructure & DevOps'
      labels:
        - 'infra'
        - 'terraform'
        - 'pipeline'
